### ISSUE TITLE
There is no 'output' directory - how does this work?

### ISSUE THREAD

**Issue by plocket** [cpina/push-to-another-repository-example#1]
> source-directory (argument)
> From the repository that this Git Action is executed the directory that contains the files to be pushed into the repository.

The example here is `source-directory: 'output'`, but I don't see a directory called 'output' in this repository. I don't see one in https://github.com/cpina/push-to-another-repository-output either. How is this repository able to push to the other one and where do those files go?

**Comment by cpina** [comment]
In the example repository:
https://github.com/cpina/push-to-another-repository-example

Via Github Action the file build.sh is executed:
https://github.com/cpina/push-to-another-repository-example/blob/master/.github/workflows/ci.yml#L18

The file build.sh generates the files in the "output" directory:
https://github.com/cpina/push-to-another-repository-example/blob/master/build.sh

These files are generated in the Github Action environment and would be lost unless are pushed to the other repository (or copied to some other server, etc.).

Hopefully this helps?

**Comment by plocket** [comment]
I think so. [The 'output' directory is created in the build.sh script.] I haven't done much generating of documents so I may be doing some stuff wrong. Is there a way to push to a directory and not just the root folder of a directory?

**Comment by plocket** [comment]
I should open that in another issue on the actual action repo. Thank you for your quick answer.
