### ISSUE TITLE
Push to subdirectory instead of repository root?

### ISSUE THREAD

**Issue by Psychokiller1888** [cpina/push-to-another-repository-example#2]
Hi!

This looks awesome, but I was wondering, because of your warning (thx for that) if this could push to a given subdirectory in the destination repository? The idea is that we dev our vue.js on a repo and I want to build it and push the build to the main repo/webui directory, and not delete the entire main repo :)

**Comment by cpina** [comment]
Sorry for the delay - I was not checking the issues in the -example repository, only in the main one.

In good news: I've just merged https://github.com/cpina/github-action-push-to-another-repository/pull/41 and I think that it does what you need :-)
