### ISSUE TITLE
fatal: could not read Password for 'https://***@github.com': No such device or address

### ISSUE THREAD

**Issue by SamSaprykin** [cpina/push-to-another-repository-example#3]
Hello! 

Today I was doing the setup your action and I ran into something that seems a bug. 

### Authentication method

Since the problem is related to an authentication problem let me give you some context before to talk about the error I have encountered. I made these steps:

E.g.: API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

Generate your personal token following the steps:

Go to the Github Settings (on the right hand side on the profile picture)

1. On the left hand side pane click on "Developer Settings"
2. Click on "Personal Access Tokens" (also available at https://github.com/settings/tokens)
3. Generate a new token, choose "Repo". Copy the token.

Then make the token available to the Github Action following the steps:

1. Go to the Github page for the repository that you push from, click on "Settings"
2. On the left hand side pane click on "Secrets"
3. Click on "Add a new secret" and name it "API_TOKEN_GITHUB"

The problem I get

My issue:

![Снимок экрана 2021-07-08 в 20 43 12](https://user-images.githubusercontent.com/38178257/125067212-9d273d00-e0bc-11eb-9e01-e2d6aaa53304.png)

The problem was that the push gave me this (meaningless) error:

![issue](https://user-images.githubusercontent.com/38178257/125067287-bb8d3880-e0bc-11eb-9d2a-8ad876b11b78.png)

### Environment Information:

- "git" version: v2.31.0 
- "node" version: v12.16.2

Project Information:

- Repository with actions: SamSaprykin/actions-test 
- Repository should get files: SamSaprykin/dest-actions 
- Author Name: Sam Saprykin 
- Author Email: saprykinse@gmail.com

Thank you!

**Comment by cpina** [comment]
Sorry for the delay answering.

Have you been able to fix the problem?

**Comment by SamSaprykin** [comment]
Hi @cpina, yeah, thanks! I had some mistake with API_TOKEN.
